# arrays multidimensionales
## indices 2d


In [109]:
# el 2d es como una tabla con filas y columnas
import numpy as np
arr2d= np.array(([0,5,10], [15, 20, 25], [30, 35, 40]))

In [110]:
arr2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [111]:
arr2d.shape

(3, 3)

In [112]:
arr2d.ndim

2

In [113]:
arr2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [114]:
# primera fila
arr2d[2]

array([30, 35, 40])

In [115]:
# primera fila y primera columna
arr2d[2, 1]

np.int64(35)

In [116]:
# ultima fil ay ultima columna
arr2d[-1,-1]

np.int64(40)

In [117]:
# editamos la primera columna en la ultima fila
arr2d[-1][0]=99

In [118]:
arr2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

## slicing 2d

In [119]:
arr2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [121]:
#subarray de filas y columnas
arr2d[:][:]

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [122]:
# subarreglo de las dos primeras filas
arr2d[:2][:]

array([[ 0,  5, 10],
       [15, 20, 25]])

In [123]:
arr2d

array([[ 0,  5, 10],
       [15, 20, 25],
       [99, 35, 40]])

In [124]:
# subarray de la primera columna
arr2d[:, :1]

array([[ 0],
       [15],
       [99]])

In [125]:
arr2d[1:, :1]

array([[15],
       [99]])

In [126]:
# edición masiva de la segunda columna
arr2d[:, 1:2] =99

In [127]:
arr2d

array([[ 0, 99, 10],
       [15, 99, 25],
       [99, 99, 40]])

In [128]:
# edicion masiva de la ultima fila
arr2d[-1, :] = [800, 200, 203]

In [129]:
arr2d

array([[  0,  99,  10],
       [ 15,  99,  25],
       [800, 200, 203]])

## fancy index
Esta técnica se basa en pasarle una lista al array haciendo referencia a las filas donde queremos acceder

In [131]:
# creamos un array 2d de ceros
arr2d = np.zeros((5, 10))

In [133]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [134]:
# modificación masiva de la primera, tercera y última fila
arr2d[[1, 2, -1]] =5

In [136]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [137]:
# podemos consultar el array a voluntad incluso repitiendo filas
arr2d[[0, 1, 1, 1,0]]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## bucles

Podemos recorrer las filas de un array con un bucle for como si de una lista se tratase:

In [138]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [139]:
for fila in arr2d:
    print(fila)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [141]:
# Utilizando enumeradores podemos sacar el índice de cada posición de la fila y el de la columna y asignarle algo:

for i, fila in enumerate(arr2d):
    for j, columna in enumerate(fila):
        arr2d[i][j]= len(fila)*i+j

In [142]:
arr2d

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49.]])


# Arrays 3D y más dimensiones
Hasta ahora hemos trabajado los arrays de 1 y 2 dimensiones, ¿será posible hacer lo mismo con 3 o más dimensiones?

El truco para manejar arrays de más dimensiones es anidar niveles de profundidad.

Vamos a recrear los 3 niveles de profundidad paso a paso para un array muy simple de 2x2x2:

In [145]:
# primer nivel con 2 de ancho
arr1d= np.array( [1, 2])

In [146]:
arr1d

array([1, 2])

In [148]:
# segundo nivel con 2 de anchp y 2 de alto
arr2d= np.array(
    [
        [1, 2],
        [3, 4]
    ]
)

In [149]:
arr2d

array([[1, 2],
       [3, 4]])

In [150]:
# tres niveles con 2 de ancho, 2 de alto y 2 de profundidad

arr3d= np.array(
    [
        [
            [1, 2], 
            [3, 4]
        ],
        [
            [5, 6], 
            [7, 8]
        ]
    ]
)

In [151]:
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [153]:
#Con esto tenemos 3 dimensiones pero podemos añadir más.

#El concepto es difícil de imaginar, nosotros únicamente percibimos 3 dimensiones pero si lo entendemos como una ramificación dónde para cada elemento hay otra lista con varios elementos, entonces podemos hacernos una idea:


# Cuarto nivel con 2 de ancho, 2 de alto, 2 de profundidad y 2 de... ¿espacio/tiempo? xD
arr_4d = np.array(
    [
        [
            [
                [1, 2],
                [3, 4]
            ],
            [
                [5, 6],
                [7, 8]
            ]
        ],
        [
            [
                [9, 10],
                [11, 12]
            ],
            [
                [13, 14],
                [15, 16]
            ]
        ]
    ]
)


In [155]:
arr_4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [157]:
# se pueden crear arreglos multidimensionales con las funciones pre-generadas

# array 3d de ceros
arr3d= np.zeros([2, 2, 2])


In [158]:
arr3d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [160]:
# array 4d de unos 2x2x2x2
arr_4d = np.ones([2,2,2,2])

In [162]:
arr_4d

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [163]:
# función reshape para formar dimensiones y tamaños
# reshape de un rango con 9 elementos a una matriz de 3x3

arr2d= np.arange(9)
arr2d

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [164]:
arr2d.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [165]:
#el número de elementos tiene que coincidir con el tamaño de las dimensiones multiplicadas:

arr3d= np.arange(9).reshape(3,2)

ValueError: cannot reshape array of size 9 into shape (3,2)

In [166]:
np.zeros([2, 2, 2, 2])

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])