# arrays transpuestos
Un array transpuesto es el reflejo de otro, de manera que las columnas se vuelven filas y las filas columna.

In [167]:
import numpy as np

In [168]:
arr= np.array([[1, 2, 3], [4, 5, 6]])

In [169]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [170]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [171]:
arr.T.T

array([[1, 2, 3],
       [4, 5, 6]])

In [172]:
#La función swapaxes sirve para intercambiar la posición de los dos ejes de un array, así que sirve para lo mismo:

# intercambiar filas x columnas
arr.swapaxes(0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [174]:
# podemos encontrar el array transpuesto de un array de 3 o más dimensiones
arr3d= np.arange(8)

In [175]:
arr3d

array([0, 1, 2, 3, 4, 5, 6, 7])

In [176]:
arr3d= arr3d.reshape(2, 2, 2)
arr3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [180]:
arr3d.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [182]:
# intercambiar los ejes con swapaxes, por ejemplo la primera dimensión por la tercera, que en nuestro caso sería equivalente al array transpuesto:

arr3d.swapaxes(0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [183]:
# no sería equivalente intercambiar la primera x la segunda
arr3d.swapaxes(0,1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])