# Arreglos pregenerados
## arreglo de ceros

In [1]:
# es cuando todos sus elementos son ceros, se genera con el método zeros

In [2]:
from array import array

import numpy as np

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
# se pueden hacer arreglos multidimensionales
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros([2, 2])

array([[0., 0.],
       [0., 0.]])

# arreglo de unos
### usando el método ones

In [14]:
np.ones([2, 3])

array([[1., 1., 1.],
       [1., 1., 1.]])

# arreglo de identidad

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Arreglo de rangos

In [18]:
list(range(4))

[0, 1, 2, 3]

In [20]:
np.arange(4)
# rango de 0 a 4

array([0, 1, 2, 3])

In [22]:
np.arange(4.)
# rango con decimales

array([0., 1., 2., 3.])

In [24]:
# rango de -3 a 3
np.arange(-3, 3)

array([-3, -2, -1,  0,  1,  2])

In [25]:
# rango de 20 números a partir de 0 cada 5 números
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])