In [55]:
import numpy as np
int('5')
arreglo = np.array([1, 2, 3, 4, 5])
arreglo
type(arreglo)


numpy.ndarray

# Dimensión y forma

In [56]:
print(arreglo)

[1 2 3 4 5]


In [57]:
arreglo.ndim

1

In [58]:
arreglo.shape

(5,)

In [59]:
arreglo =  np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
])
print(arreglo)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [60]:
arreglo.ndim
# esto es para el número de dimensiones wuuuu

2

In [61]:
arreglo.shape
#este nos dice la forma, 2 filas x 5 columnas

(2, 5)

# Tipos de datos

In [62]:
arreglo = np.array([1, 2, 3, 4, 5])

In [63]:
arreglo.dtype 
# nos dice que es un entero de 64 bits

dtype('int64')

In [64]:
arreglo = np.array([1, 2, 3, 4, 5, 6.1234])

In [65]:
arreglo.dtype
# nos dice que es un flotante

dtype('float64')

# Almacenar cadenas

In [66]:
arreglo = np.array(["Hola", "como", "estas"])

In [67]:
arreglo.dtype
# nos indica que el arreglo es un unicode, o sea, que tiene símbolos de escritura

dtype('<U5')

In [68]:
arreglo =  np.array(["hola", 123436, 3.43863])

In [69]:
arreglo.dtype

dtype('<U32')

In [70]:
arreglo
# los arreglos no son listas, son estructuras que almacenan vectores y matrices, son conscientes en t0do momento de su dimensión, forma y tipo de datos

array(['hola', '123436', '3.43863'], dtype='<U32')

# Tablas y gráficos

In [71]:
import numpy as np
import pandas as pd

In [72]:
tabla = pd.DataFrame(
    np.random.randint(0, 100, size = (4, 3)),
    columns = ['pepe', 'maria', 'jose'])
tabla

pepe  maria  jose
0    38      2    66
1    88     63    42
2    79     99    11
3    29     64    24