# funciones universales
Se llaman así porque sirven para aplicar funciones matemáticas comunes en los elementos.
Podemos encontrar:

Operaciones matemáticas
Operaciones trigonométricas
Operaciones comparativas
Operaciones flotantes
Operaciones de intercambio de bits

## matemáticas

In [184]:
import numpy as np

In [187]:
# array de prueba
arr1 = np.arange(1, 6)
arr2= np.array([-3,7,3,13,0])

In [188]:
arr1

array([1, 2, 3, 4, 5])

In [189]:
arr2

array([-3,  7,  3, 13,  0])

In [190]:
# suma
np.add(arr1,arr2)

array([-2,  9,  6, 17,  5])

In [191]:
#resta
np.subtract(arr2,arr1)

array([-4,  5,  0,  9, -5])

In [192]:
arr1

array([1, 2, 3, 4, 5])

In [194]:
# raiz cuadrada
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [196]:
# potencia
np.power(arr1,2)

array([ 1,  4,  9, 16, 25])

In [197]:
arr1

array([1, 2, 3, 4, 5])

In [198]:
arr2

array([-3,  7,  3, 13,  0])

In [199]:
 # signo
 np.sign(arr2)

array([-1,  1,  1,  1,  0])

# trigonometricas

In [200]:
arr1

array([1, 2, 3, 4, 5])

In [201]:
np.pi

3.141592653589793

In [202]:
# seno
np.sin(arr1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [204]:
# coseno
np.cos(arr1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [206]:
#tangente
np.tan(arr1)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [208]:
#grados a radianes
np.deg2rad(arr1)

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646])

In [210]:
# radianes a grados
np.rad2deg(arr1)

array([ 57.29577951, 114.59155903, 171.88733854, 229.18311805,
       286.47889757])

# comparativas

In [212]:
def convert_grad_2_radians(param1: int, param2: np.array, **kwards):
    """
    description of the function
    params:
    param1: int what is used for
    param2: int what is used for
    kwards: contains list of params to be used for the model
    outputs:
    
    """
    pass

In [213]:
arr1, arr2

(array([1, 2, 3, 4, 5]), array([-3,  7,  3, 13,  0]))

In [215]:
# maximo
np.maximum(arr1, arr2)

array([ 1,  7,  3, 13,  5])

In [217]:
# inimo
np.minimum(arr1, arr2)

array([-3,  2,  3,  4,  0])

In [219]:
#igual que
np.equal(arr1, arr2)

array([False, False,  True, False, False])

In [220]:
arr1, arr2

(array([1, 2, 3, 4, 5]), array([-3,  7,  3, 13,  0]))

# flotantes

In [223]:
# tercer array de prueba
arr3= np.array([3.14, 2.44, -6.3, 0.3472, 43.3])


In [224]:
# valor absoluto
np.fabs(arr3)

array([ 3.14  ,  2.44  ,  6.3   ,  0.3472, 43.3   ])

In [226]:
# techo -> redondeo hacia arriba
np.ceil(arr3)

array([ 4.,  3., -6.,  1., 44.])

In [227]:
# suelo -> redondeo hacia abajo
np.floor(arr3)

array([ 3.,  2., -7.,  0., 43.])