# gestión de arrays

In [78]:
import numpy as np

In [79]:
arr = np.arange(0, 50, 5)

In [80]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [82]:
# El índice en los arrays funciona exactamente igual que en las listas, es simplemente un número que hace referencia a la posición que queremos consultar o modificar, empezando éste a contarse en 0:

arr[0]

np.int64(0)

In [85]:
# quinta posición
arr[4]


np.int64(20)

In [86]:
# ultima posición
arr[-1]

np.int64(45)

In [87]:
# asignar un valor
arr[-1] = 99

In [88]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 99])

# slicing

In [89]:
# Igual con las listas, el slicing nos permite acceder y modificar un rango en base a dos índices, uno de inicio y otro de fin separados por dos puntos. Si dejamos los índices vacíos se toman por defecto el principio y el final:


# copiar completo de principio a fin
arr[:]

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 99])

In [91]:
# subarray de los 3 primeros elementos
arr[:3]

array([ 0,  5, 10])

In [92]:
# modificar rango de forma masiva menos primero y último
arr[3:-1] =50

In [93]:
arr

array([ 0,  5, 10, 50, 50, 50, 50, 50, 50, 99])

## consideraciones importantes

In [94]:
# Los arrays son objetos y por tanto se encuentran referenciados en la memoria.

#A la hora de trabajar con subarrays todos los cambios que hagamos en ellos se verán reflejados en el array original:

# crear un nuevo arreglo

arr= np.arange(0, 30, 3)

In [95]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [96]:
#extraemos un subarray
subarr= arr[0:4]

In [97]:
subarr

array([0, 3, 6, 9])

In [98]:
# se modifica
subarr[:]=99
subarr

array([99, 99, 99, 99])

In [99]:
# a ver el arreglo original
arr

array([99, 99, 99, 99, 12, 15, 18, 21, 24, 27])

## copia de arrays
Mediante el método copy podemos crear una copia, de manera que tengamos dos objetos y los cambios del subarray ya no afecten al original:

In [100]:
# crear un nuevo array
arr = np.arange(0, 30, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [102]:
# extraer el subarray de una copia
subarr =  arr[0:4].copy()
subarr

array([0, 3, 6, 9])

In [103]:
# mo dificamos
subarr[:] =99

In [104]:
subarr

array([99, 99, 99, 99])

In [106]:
# veamos el array original
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])