# Operaciones básicas

## suma

In [27]:
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]

In [29]:
lista1+lista2

[1, 2, 3, 4, 5, 6]

In [33]:
import numpy as np
# dos arreglos
arr1= np.array([1, 2, 3, 4])
arr2= np.array([5, 6, 7, 8])

# se suman
arr1+arr2

array([ 6,  8, 10, 12])

In [35]:
# si los arreglos no tienen la misma forma, entonces no se pueden sumar

arr3= np.array([9, 10])
arr2 + arr3 ## sale error

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

## Resta

In [36]:
arr1, arr2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [38]:
arr1 - arr2

array([-4, -4, -4, -4])

In [41]:
arr1-arr1

array([0, 0, 0, 0])

## producto

In [46]:
arr1= np.array([1, 2, 3, 4])
arr2= np.array([2, 3, 4, 5])

# los multiplicamos
arr1*arr2

array([ 2,  6, 12, 20])

In [48]:
# multiplicar un array por un número
arr1*10

array([10, 20, 30, 40])

In [50]:
np.array(10)

array(10)

In [51]:
arr1

array([1, 2, 3, 4])

In [53]:
arr1*np.array(10)

array([10, 20, 30, 40])

## división

In [54]:
arr1, arr2

(array([1, 2, 3, 4]), array([2, 3, 4, 5]))

In [55]:
arr1/arr2

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [56]:
# se puede obtener el arreglo inverso dividiendo entre 1 el array
arr1

array([1, 2, 3, 4])

In [57]:
1/arr1

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [59]:
# sacar la inversa es igual a sacar la potencia -1
## peeeero, no se puede hacer jejeje
arr1 ** -1

ValueError: Integers to negative integer powers are not allowed.

In [61]:
type(1.)

float

## potencia

In [62]:
arr1, arr2

(array([1, 2, 3, 4]), array([2, 3, 4, 5]))

In [63]:
arr1**arr2

array([   1,    8,   81, 1024])

## operaciones en arrays 2D

In [65]:
arr5 = np.array([[1, 2], [3, 4]])
arr6 = np.array([[5, 6], [7, 8]])

arr5, arr6

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [66]:
arr5 + arr6

array([[ 6,  8],
       [10, 12]])

In [68]:
arr5*3

array([[ 3,  6],
       [ 9, 12]])

In [69]:
arr5

array([[1, 2],
       [3, 4]])

In [70]:
vec = np.array([5, 10])
vec

array([ 5, 10])

In [71]:
'dimension', vec.ndim, 'forma:', vec.shape

('dimension', 1, 'forma:', (2,))

In [73]:
vec.transpose()

array([ 5, 10])

In [75]:
arr5*(vec.T)

array([[ 5, 20],
       [15, 40]])

In [76]:
arr5 @ (vec.T)

array([25, 55])

In [77]:
arr5 * np.array([5, 10, 15])

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 